# Runs Python Tests
name: Python Tests

on: [push, pull_request]

jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install and Configure poetry
      run: |
        cd /api
        python -m pip install poetry==1.8.2
        python -m poetry config virtualenvs.in-project true

    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: ./api/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/api/poetry.lock') }}

    - name: Install dependencies
      run: |
        cd /api
        python -m poetry install

    - name: Run tests
      run: |
        cd /api
        python -m poetry run python -m pytest --disable-warnings -xv --cov=. --cov-report=xml
